"""add note updated at

Revision ID: 6452a5405981
Revises: cd62a9130ea6
Create Date: 2026-08-29 14:02:44.168542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6452a5405981'
down_revision: Union[str, Sequence[str], None] = 'cd62a9130ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'notes',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE notes SET updated_at = created_at WHERE updated_at IS NULL"
    )

    op.alter_column(
        'notes',
        'updated_at',
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    # ### end Alembic commands ###
