"""add quantities and formulas

Revision ID: bac75b933ed0
Revises: d85bf2de07ed
Create Date: 2026-09-21 08:16:08.514005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac75b933ed0'
down_revision: Union[str, Sequence[str], None] = 'd85bf2de07ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('result_unit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='fk_formulas_note_id_notes', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_unit_id'], ['units.id'], name='fk_formulas_result_unit_id_units'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'name', name='uq_formulas_note_id_name')
    )
    op.create_index(op.f('ix_formulas_note_id'), 'formulas', ['note_id'], unique=False)
    op.create_table('quantities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=38, scale=20), nullable=False),
    sa.Column('uncertainty', sa.Numeric(precision=38, scale=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='fk_quantities_note_id_notes', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='fk_quantities_unit_id_units'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quantities_note_id'), 'quantities', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quantities_note_id'), table_name='quantities')
    op.drop_table('quantities')
    op.drop_index(op.f('ix_formulas_note_id'), table_name='formulas')
    op.drop_table('formulas')
    # ### end Alembic commands ###
