"""add units table

Revision ID: d85bf2de07ed
Revises: 6452a5405981
Create Date: 2026-09-17 11:55:31.001009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd85bf2de07ed'
down_revision: Union[str, Sequence[str], None] = '6452a5405981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('dimension', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('factor', sa.Numeric(precision=38, scale=20), nullable=False),
    sa.Column('offset', sa.Numeric(precision=38, scale=20), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('base_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(
        ['base_unit_id'],
        ['units.id'],
        name='fk_units_base_unit_id_units',
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_symbol'), 'units', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_symbol'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
